### ISSUE TITLE
Een lid verwijderen van mijnROOD verwijdert het lid niet uit de Mollie database

### ISSUE THREAD

**Issue by pingiun** [roodjong/mijnrood#101]
Zie ook #47

**Comment by KiaraGrouwstra** [comment]
mollie heeft een api die zooi hiermee kan

**Comment by KiaraGrouwstra** [comment]
handmatig kan je daar ook mee interacteren via bv postman:
https://code.bij1.org/bij1/wiki/wiki/mollie_mandaten_intrekken
overigens is een pitfall bij Mollie dat hun web UI enkel een knop 'klant verwijderen' biedt, die denk ik niet strookt met onze bewaarplicht onder wet financiering politieke partijen.

**Comment by Gwildor** [comment]
Gezien we ook lidmaatschapstype nu hebben in plaats van het verwijderen van leden, lijkt het met nuttig als hier een hele aparte pagina/actie voor komt om dit voor het lid te doen.

@rrooij waar is jouw code om de automatische incasso stop te zetten?

**Comment by Gwildor** [comment]
Deze aparte actie bij een lid om het abonnement te annuleren hebben we inmiddels al een tijdje, dus deze kan dicht.
