### ISSUE TITLE
Contributie kan worden stopgezet maar niet daarna worden ingesteld voor een andere rekening

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [roodjong/mijnrood#12]
Automatisch incasso kan worden ingeschakeld, en daarna ook uitgeschakeld. Maar daarna kan je dus alleen weer opnieuw inschakelen voor de rekening waarop je eerder hebt ingesteld. Na uitschakelen linkt de inschakelen knop niet door na de pagina waar je een eerste betaling kan doen maar schakelt gewoon direct in. In effect kun je dus niet je rekeningnummer wijzigen.

**Comment by Martionex** [comment]
Dit heeft erg hoge prio momenteel, omdat we leden straks gaan uitschrijven wanneer ze geen contributie betalen

**Comment by AndrewAmmerlaan** [comment]
Het verwijderen uit Mollie is geen goede workaround want veroorzaakt dat mensen uberhaupt geen contributie meer kunnen betalen.

**Comment by AndrewAmmerlaan** [comment]
Resolved en is nu ook live
