### ISSUE TITLE
Contactpersonen/afdelingsvoorzitters moeten toegang tot de beheeromgeving krijgen

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#140]
In de branch `socialisten_landelijk` is code toegevoegd om afdelingsvoorzitters toegang te geven tot de beheeromgeving. Daarbij hebben zij alleen toegang tot de leden uit hun eigen afdeling. Deze functionaliteit moet gekopieerd worden naar `main`.

Deels is dit mogelijk al opgevangen door https://github.com/roodjong/mijnrood/pull/139. Kijk wat hiervan herbruikbaar is.

[Link naar de diff tussen de laatste commits van `main` en `socialisten_landelijk`](https://github.com/roodjong/mijnrood/compare/f99328b...13ef9fb)

**Acceptatie criteria**

- [ ] De benodigde code is gekopieerd naar `main` en werkt
- [ ] De rest van de functionaliteiten werken nog
- [ ] De benodigde configuratie of aanpassingen aan huidige code zijn toegepast om bestaande functionaliteiten niet in de weg te zitten of de nieuwe functionaliteit uit te schakelen

**Comment by rrooij** [comment]
Deze zit al in `main`

Om te reproduceren:

1. Zet de omgeving op zoals de readme
2. Login met de test-user: 3 en met wachtwoord `contact`
3. Deze gebruiker kan in het beheersysteem en enkel de leden zien van diens groep
