### ISSUE TITLE
Email versturen bij inschrijving zowel naar nieuw lid als naar groep ter bevestiging

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#141]
Op dit moment worden in de verschillende branches op verschillende momenten emails verstuurd. Dit moet gelijkgetrokken worden. We willen in ieder geval:

- [ ] Een mail naar het nieuwe lid op moment van inschrijving
- [ ] Een mail naar de contactpersonen van de groep zodat zij op de hoogte zijn van de inschrijving
- [ ] Een mail naar het nieuwe lid op moment van goedkeuring van inschrijving

De code hiervoor kan je kopieren van de verschillende branches, eveneens als de templates. Indien een template nog niet bestaat, moet die gemaakt worden.

Deze issue is op te delen in 3en door de mails los te doen.

## Oude beschrijving:
De branch `main` bevat code die een mail stuurt naar de contactpersoon van de groep waar een nieuw lid zich heeft ingeschreven. In `socialisten_landelijk` is deze code weggehaald, of lijkt deze functionaliteit verplaatst te zijn naar de `MemberController`. Deze functionaliteit moet configureerbaar zijn. Het liefste wordt er een mail gestuurd naar een configureerbaar mailadres per groep. Als dat te moeilijk is, moet deze functionaliteit blijven zoals die is, en met een globale feature flag uitgeschakeld kunnen worden.

De branch `socialisten_landelijk` bevat wel soortgelijke code in de `apply` functie van de `MemberController`. Indien mogelijk moet deze code samengevoegd worden.

[Link naar de diff tussen de laatste commits van `main` en `socialisten_landelijk`](https://github.com/roodjong/mijnrood/compare/f99328b...13ef9fb)

**Acceptatie criteria**

- [ ] De benodigde code is gekopieerd naar `main` en werkt
- [ ] De rest van de functionaliteiten werken nog
- [ ] De benodigde configuratie of aanpassingen aan huidige code zijn toegepast om bestaande functionaliteiten niet in de weg te zitten of de nieuwe functionaliteit uit te schakelen

**Comment by rrooij** [comment]
Voor de helderheid, is er een organisatie die dit niet wil? In dat geval kan de status quo behouden worden.

**Comment by Gwildor** [comment]
Ik weet niet wat dit/de status quo is, dus geen idee.

Wat mij betreft gaat de mail over een nieuwe aanmelding naar:

1. ofwel naar een mailadres van de groep/afdeling, dus onderdeel van de `Division` model (er is een `Email` veld nu maar ik weet niet of die gebruikt wordt)
1. ofwel naar de privé-emails van alle personen die toegang hebben tot de beheeromgeving (dus het veld `contacts` op `Division`.
 
Het is mij om het even welke van die twee. `main` en `socialisten_landelijk` hebben beide code hiervoor, maar ik weet niet wat ze doen, en ze zijn verschillend. Dat moet rechtgetrokken worden, vandaar deze issue.

**Comment by Gwildor** [comment]
Het is nu onduidelijk welke mails er allemaal zijn. Er is `welcome.twig` met de meest uitgebreide welkomstmail naar het lid dat zich ingeschreven heeft. Verder is er `apply.twig` in de Socialisten branch met een korte uitleg dat het lid eerst goedgekeurd moet worden, maar `main` heeft deze niet en moet deze waarschijnlijk wel krijgen.

Verder moet in ieder geval bij inschrijving, en eventueel ook bij goedkeuring, een mail gestuurd worden naar de groep/afdeling dat er een lid is dat op goedkeuring wacht. Zie mijn reactie hierboven voor hoe dat geconfigureerd moet worden. Het lijkt erop dat dit in `main` alleen bij goedkeuring gebeurt, niet bij inschrijving.

**Comment by AndrewAmmerlaan** [comment]
Als ik mij goed herinner hadden wij een keer omgegooid wanneer iemand de mail krijgt (bij aanmelding, versus bij acceptatie). Ik weet niet meer waarom we dit hadden gedaan, en of en hoe dit is gepropageerd naar dS.

**Comment by Gwildor** [comment]
Ik heb de issue geupdatet. We willen gewoon in elke situatie een mailtje. Mail bij inschrijving kan vrij kort zijn, met gewoon dankwoord en "je wordt nog goedgekeurd door je groep/afdeling"
