### ISSUE TITLE
Welkomstmail moet configureerbaar zijn

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#146]
De branches `main` en `socialisten_landelijk` hebben ieder een andere inhoud voor `templates/email/html/welcome.html.twig` en `templates/email/text/welcome.txt.twig`. Deze moet configureerbaar zijn per instantie. Desnoods door ze andere bestandsnamen te geven.

[Link naar de diff tussen de laatste commits van `main` en `socialisten_landelijk`](https://github.com/roodjong/mijnrood/compare/f99328b...13ef9fb)

**Acceptatie criteria**

- [ ] De benodigde code is gekopieerd naar `main` en werkt
- [ ] De rest van de functionaliteiten werken nog
- [ ] De benodigde configuratie of aanpassingen aan huidige code zijn toegepast om bestaande functionaliteiten niet in de weg te zitten of de nieuwe functionaliteit uit te schakelen

**Comment by rrooij** [comment]
De nette manier is denk ik een template die via de GUI is te configureren in het adminpaneel door de globale admins die vervolgens wordt opgeslagen in de database.

Mijn idee is om een aantal placeholders te introduceren bijvoorbeeld _NAME_. Vervolgens vervangen we die bij het versturen van een mail door de echte gegevens. Misschien is zelfs enkel _NAME_ nodig?

Een Twig template vervangen of aanpassen lijkt me iets teveel van het goede, want dan worden de beheerders van de applicatie continu gevraagd om updates te doen. En misschien is er dan ook risico op arbitraire code execution via Twig? Hier ben ik niet zeker van maar moeten we voorzichtig mee zijn.

**Comment by Gwildor** [comment]
Een tabel met mailtemplates met een vaste naam die aanpasbaar zijn in de UI lijkt me op zich een goed idee. Maar het is wel belangrijk om zo snel mogelijk deze milestone af te maken, dus ik wil er wel voor waken dat we niet onnodig aan het overengineeren zijn waardoor het niet af komt. Maar er zijn denk ik wel meerdere templates die aangepast moeten worden, dus wellicht is het een goede manier om in 1 klap alles op te lossen.

Voor templates zou je kunnen kijken naar [Mustache](https://mustache.github.io/mustache.5.html). Dat is een vrij lichte templatetaal wat het risico's op code execution verkleint.

Verder moet je eraan denken dat elke template twee versies heeft: een versie met platte tekst en een versie met html, voor de mailclients die html wel/niet ondersteunen.

**Comment by Gwildor** [comment]
Opgelost in #169
