### ISSUE TITLE
Toevoegen lidmaatschapstatus

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#147]
De branch `platcom` bevat code de statussen van lidmaatschap van leden die in de beheeromgeving configureerbaar is. Deze functionaliteit moet gekopieerd worden naar `main`.

[Link naar de diff tussen de laatste commits van `socialisten_landelijk` en `platcom`](https://github.com/roodjong/mijnrood/compare/13ef9fb...22ce792)

**Acceptatie criteria**

- [ ] De benodigde code is gekopieerd naar `main` en werkt
- [ ] De rest van de functionaliteiten werken nog
- [ ] De benodigde configuratie of aanpassingen aan huidige code zijn toegepast om bestaande functionaliteiten niet in de weg te zitten of de nieuwe functionaliteit uit te schakelen

**Comment by rrooij** [comment]
Commit met de entiteiten en CRUDController https://github.com/roodjong/mijnrood/commit/5f388d6e85951bed2d8f2a3f34bf696f71dbe07d

**Comment by rrooij** [comment]
See PR #154

**Comment by Gwildor** [comment]
@rrooij deze kan dan dicht, toch?

**Comment by rrooij** [comment]
Yes
