### ISSUE TITLE
Sorteren van bestanden

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#150]
De branches `socialisten_landelijk` en `platcom` hebben code voor het automatisch sorteren van bestanden op de documentenpagina. Deze moet gekopieerd worden naar `main`.

[Link naar de diff tussen de laatste commits van `socialisten_landelijk` en `platcom`](https://github.com/roodjong/mijnrood/compare/13ef9fb...22ce792)

**Acceptatie criteria**

- [ ] De benodigde code is gekopieerd naar `main` en werkt
- [ ] De rest van de functionaliteiten werken nog
- [ ] De benodigde configuratie of aanpassingen aan huidige code zijn toegepast om bestaande functionaliteiten niet in de weg te zitten of de nieuwe functionaliteit uit te schakelen

**Comment by rrooij** [comment]
Commit 61c9873be05f08d6e0534a7d2b1a1950ee6a3fca contains the sorting of documents and commit 0d8de373da32d5e8b4ede3d2077ae125bfebb288 sorting of folders

**Comment by rrooij** [comment]
It seems like documents are already sorted. At least, when I run the latest `main` branch and upload a bunch of files and folders, they are sorted alphabetically even when I upload them in reverse order.
