### ISSUE TITLE
Remove ListMonk URL

### ISSUE THREAD

**Issue by rrooij** [roodjong/mijnrood#153]
Currently the `main` branch includes a ListMonk entry in the sidebar on the `/admin` page. This should be optional as not every organization needs a ListMonk entry there.

Introduced in: https://github.com/roodjong/mijnrood/commit/fd9d8dba0a275684034e160632a60d6ce3896d02

**Comment by Gwildor** [comment]
I think it can be removed, as Jelle confirmed on Whatsapp that not even ROOD is currently using ListMonk.

**Comment by Gwildor** [comment]
Fixed by #184
