### ISSUE TITLE
Laat nieuwe leden direct contributie invullen

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#155]
Op dit moment moeten nieuwe leden goedgekeurd worden door hun groep of afdeling voordat ze gevraagd wordt om hun contributie in te stellen. Hierdoor doen veel nieuwe leden dit nooit, en moeten zij benaderd worden om dit alsnog te doen. Hierdoor lopen we momenteel veel contributie mis.

Het makkelijkste om dit snel op te lossen is denk ik om de contributiepagina open te stellen voor ongeverifieerde leden, en nieuwe leden naar deze pagina te sturen nadat het inschrijfformulier is ingevuld. Wel is het denk ik goed om dan een begeleidende extra tekst toe te voegen, iets in de trant van "je inschrijving is gelukt, je groep/afdeling neemt binnenkort contact op. We vragen je hieronder je contributie in te stellen".

Een nadeel hiervan is dat je, als het lid geweigerd wordt, de contributie weer moet stopzetten en/of terugdraaien, maar dat is iets dat nu ook al moet bij leden die zich uitschrijven. Ook kan het nieuwe lid gewoon de pagina sluiten na het inschrijven zonder de contributie in te stellen, maar dat is gelijk aan de huidige situatie.

**Comment by rrooij** [comment]
In de main branch die voor ROOD gebruikt wordt is het de status quo dat je eerst contributie moet instellen voordat je lid kan worden. Toch @JordiVanOs ?

**Comment by Gwildor** [comment]
Ik zie het in het aanmeldformulier inderdaad, interessant. Lijkt me betere manier ja, we moeten als onderdeel van #144 kijken of dat behouden kan worden en dan kan deze dicht.

**Comment by Gwildor** [comment]
Ik sluit deze omdat dit dus al in main zit.
