### ISSUE TITLE
Veld toevoegen op aanmeldpagina: Hoe ben je bij ROOD gekomen?

### ISSUE THREAD

**Issue by JordiVanOs** [roodjong/mijnrood#171]
Op de kaderdag van 11 mei 2024 kwam de suggestie dat ROOD in staat moet zijn om te reflecteren op hoe mensen bij onze organisatie komen. Laten we een veld toevoegen op de aanmeldpagina zodat we kunnen zien hoe een lid in contact is gekomen met ons. Mogelijk is een dropdown genoeg, of anders een vrij invoerveld.

Deze info kan ook bruikbaar zijn om het toe te voegen als veld aan dat van het lid zelf, zodat ook na het accepteren van de aanmelding het inzichtelijk is voor e.g. contactpersonen en het bestuur.

**Comment by pingiun** [comment]
We hebben deze issue besproken tijdens de hackathon. We hebben besloten deze issue te deprioriteren om te focussen op onderhoud en bugfixes.
