### ISSUE TITLE
Mollie abonnement annuleren geeft soms een fout

### ISSUE THREAD

**Issue by Gwildor** [roodjong/mijnrood#208]
Bij bewerken van een lid heb je een optie om een Mollie abonnement te annuleren, wat noodzakelijk is voor het uitschrijven van een lid.

Je krijgt een 500 Internal Server Error op de website. Het is helaas onbekend wat de fout is.

Extra: graag de labels iets duidelijker maken dat het om contributie gaat.
Extra: Als het abonnement al geannuleerd is, krijg je een hele simpele melding dat het abonnement al geannuleerd is. Die zou mooier mogen, bijv als flash message.

**Comment by LukaBerkers** [comment]
Fixed by #215
