### ISSUE TITLE
Generated links are http

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [roodjong/mijnrood#89]
When asking for e.g. a password reset, you'll get a http link in the email instead of a https link.

**Comment by pingiun** [comment]
het probleem doet zich ook voor op de documenten pagina, je krijgt de volgende error in google chrome: 

<img width="975" alt="image" src="https://user-images.githubusercontent.com/1576660/207426127-28709d34-3628-4d5e-a5a2-d323fca05b48.png">

**Comment by pingiun** [comment]
Fixed by setting `SECURE_SCHEME` to `https` in the .env.local and doing #98
